apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-conf
  namespace: default
data:
  config.yaml: |
        rules_folder: rules

        run_every:
          minutes: 1

        buffer_time:
          minutes: 15

        es_host: 192.168.99.100
        es_port: 31389
        use_ssl: False

        writeback_index: elastalert_status
        writeback_alias: elastalert_alerts

        alert_time_limit:
          days: 2
